### ISSUE TITLE
401 Unauthorized error when doing certain actions like sending guild messages

### ISSUE THREAD

**Issue by catamari** [Hawxy/Discord.Addons.Hosting#20]
I spent 2 days banging my head against the wall trying to figure this out but because I apparently can't read I didn't realize dnet-labs had a separate package.

I just wanted to make and resolve this issue so that if anyone else follows in my footsteps they might hopefully come across this issue and not waste as much time as I did.

**Comment by Taifunov** [comment]
@tstaples are you solved this problem? Coz i have the same after updating ...
