### ISSUE TITLE
Support for HostApplicationBuilder

### ISSUE THREAD

**Issue by d4n3436** [Hawxy/Discord.Addons.Hosting#29]
.NET Platform Extensions 7 introduced a new way of creating host builders using `Host.CreateApplicationBuilder()`, which returns a `HostApplicationBuilder` object. The extension methods on the project only work on `IHostBuilder`, though.
Is there any chance this new API will be supported?

Documentation: https://learn.microsoft.com/en-us/dotnet/core/extensions/generic-host?tabs=appbuilder

**Comment by Hawxy** [comment]
I was actually looking into this a few days ago. Will have a new release out today with the relevant changes.
